=== pavan4030/app-utils/jde-system-api/src/main/api/CreateOrUpdateCustomer-Schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"type": "object",
	"properties": {
		"id": {
			"type": "string",
			"minLength": 1,
			"maxLength": 40
		},
		"doNotCall": {
			"type": "string",
			"enum": ["Y", "N"]
		},
		"doNotText": {
			"type": "string",
			"enum": ["Y", "N"]
		},
		"doNotEmail": {
			"type": "string",
			"enum": ["Y", "N"]
		},
		"dateOfBirth": {
			"type": ["string", "null"],
			"pattern": "(0?[1-9]|1[012])/(0?[1-9]|[12][0-9]|3[01])/((19|20)\\d\\d)"
		},
		"phoneDetails": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"phoneNumber": {
						"type": "string",
						"minLength": 1,
						"maxLength": 40
					},
					"type": {
						"type": "string",
						"minLength": 1,
						"maxLength": 40
					},
					"preferredPhone": {
						"type": "string",
						"enum": ["Y", "N"]
					}

				},
				"required": [
					"phoneNumber",
					"type",
					"preferredPhone"

				]
			},
			"minItems": 1
		},
		"emailDetails": {
			"type": ["array","null"],
			"items": {
				"type": "object",
				"properties": {
					"emailAddress": {
						"type": "string",
						"minLength": 1,
						"maxLength": 40
					},
					"type": {
						"type": "string",
						"minLength": 1,
						"maxLength": 40
					},
					"preferredEmail": {
						"type": "string",
						"enum": ["Y", "N"]
					}

				},
				"required":[
				"emailAddress",
				"type",
				"preferredEmail"
				]
			}
		},
		"tccAccountNumber": {
			"type": "string",
			"minLength": 1,
			"maxLength": 40
		},
		"firstName": {
			"type": "string",
			"minLength": 1,
			"maxLength": 40
		},
		"lastName": {
			"type": "string",
			"minLength": 1,
			"maxLength": 40
		},
		"employerName": {
			"type": ["string", "null"],
			"maxLength": 40
		},
		"jobTitle": {
			"type": ["string", "null"],
			"maxLength": 40
		},
		"lastActivity": {
			"type": ["string", "null"],
			"pattern": "(0?[1-9]|1[012])/(0?[1-9]|[12][0-9]|3[01])/((19|20)\\d\\d)"
		},
		"lastPurchaseDate": {
			"type": ["string", "null"],
			"pattern": "(0?[1-9]|1[012])/(0?[1-9]|[12][0-9]|3[01])/((19|20)\\d\\d)"
		},
		"login": {
			"type": "string",
			"maxLength": 40
		},
		"registrationDate": {
			"type": "string",
			"pattern": "(0?[1-9]|1[012])/(0?[1-9]|[12][0-9]|3[01])/((19|20)\\d\\d)"
		},
		"customerType": {
			"type": "string",
			"enum": ["CONSUMER", "BUSINESS"]
		},
		"notes": {
			"type": ["string", "null"]
		},
		"employeeId": {
			"type": ["string", "null"]
		},
		"storeId": {
			"type": ["string", "null"]
		},
		"verizonDetails": {
			"type": ["null", "object"],
			"properties": {
				"verizonAccountNumber": {
					"type": "string",
					"minLength": 1,
					"maxLength": 40
				}
			},
			"required": [
				"verizonAccountNumber"
			]
		},
		"businessDetails": {
			"type": ["null", "object"],
			"properties": {
				"businessName": {
					"type": "string",
					"minLength": 1
					
				},
				"taxExemptNumber": {
				"type": ["null", "string"],
					"maxLength": 40
				}
			},
			"required": [
				"businessName"
			]
		},
		"authorizedUsers": {
			"type": ["null", "object"],
			"properties": {
				"name": {
					"type": "string",
					"minLength": 1,
					"maxLength": 40
				}
			},
			"required": [
				"name"
			]
		},
		"homeAddress": {
			"type": ["null", "object"],
			"properties": {
				"Id": {
					"type": "string",
					"maxLength": 40
				},
				"address1": {
					"type": "string",
					"maxLength": 40
				},
				"address2": {
					"type": "string",
					"maxLength": 40
				},
				"city": {
					"type": "string",
					"maxLength": 40
				},
				"state": {
					"type": "string",
					"maxLength": 40
				},
				"postalCode": {
					"type": "string",
					"maxLength": 40
				},
				"country": {
					"type": "string",
					"maxLength": 40
				},
				"doNotMail": {
					"type": "string",
					"enum": ["Y", "N"]
				}
			},
			"required": [
				"doNotMail"
			]
		},
		"shippingAddress": {
			"type": ["null", "object"],
			"properties": {
				"Id": {
					"type": "string",
					"maxLength": 40
				},
				"address1": {
					"type": "string",
					"maxLength": 40
				},
				"address2": {
					"type": "string",
					"maxLength": 40
				},
				"city": {
					"type": "string",
					"maxLength": 40
				},
				"state": {
					"type": "string",
					"maxLength": 40
				},
				"postalCode": {
					"type": "string",
					"maxLength": 40
				},
				"country": {
					"type": "string",
					"maxLength": 40
				},
				"doNotMail": {
					"type": "string",
					"enum": ["Y", "N"]
				}
			},
			"required": [
				"doNotMail"
			]
		}
	},
	"required": [
		"id",
		"phoneDetails",
		"tccAccountNumber",
		"firstName",
		"lastName",
		"customerType"

	]
}

=== pavan4030/app-utils/jde-system-api/src/main/api/CreateOrUpdateCustomer.json
{
  "id": "1234568",
  "dateOfBirth": "12/12/2016",
  "doNotCall": "Y",
  "doNotText": "Y",
  "doNotEmail": "N",
  "phoneDetails": [
    {
      "phoneNumber": "151515152",
      "type": "Mobile",
      "preferredPhone": "Y"
    },
    {
      "phoneNumber": "151515152",
      "type": "Fax",
      "preferredPhone": "N"
    },
    {
      "phoneNumber": "151515152",
      "type": "Home",
      "preferredPhone": "N"
    },
    {
      "phoneNumber": "151515152",
      "type": "Work",
      "preferredPhone": "Y"
    }
  ],
  "emailDetails": [
    {
      "emailAddress": "abhi@gmail.com",
      "type": "personal",
      "preferredEmail": "Y"
    },
    {
      "emailAddress": "sure4@gmail.com",
      "type": "work",
      "preferredEmail": "N"
    }
  ],
  "tccAccountNumber": "12345678",
  "firstName": "Suresh",
  "lastName": "Tonne",
  "employerName": "Nes12",
  "jobTitle": "MTN",
  "lastActivity": "03/02/2016",
  "lastPurchaseDate": "02/29/2016",
  "login": "NA",
  "registrationDate": "02/29/2016",
  "customerType": "CONSUMER",
  "notes": "This first time testing",
  "employeeId": "12348",
  "storeId": "100100",
  "verizonDetails": {
    "verizonAccountNumber": "1234568785"
  },
  "businessDetails": {
    "businessName": "business 1",
    "taxExemptNumber": "123"
  },
  "authorizedUsers": {
    "name": "suresh"
  },
  "homeAddress": {
    "Id": "12568",
    "address1": "San",
    "address2": "Fransisco",
    "city": "carmel",
    "state": "IN",
    "postalCode": "12345",
    "country": "US",
    "doNotMail": "N"
  },
  "shippingAddress": {
    "Id": "12568",
    "address1": "San2",
    "address2": "Fransisco4",
    "city": "Carmel",
    "state": "IN",
    "postalCode": "12356",
    "country": "US",
    "doNotMail": "Y"
  }
}
